spring:
  application:
    name: risk-rating-model
  profiles:
    active: localdev
  jackson:
    default-property-inclusion: always
  data:
    rest:
      base-path: /api
server:
  servlet:
    context-path: /risk